### ISSUE TITLE
How to keep the same color for two or more plots

### ISSUE THREAD

**Issue by Yoorthiziri** [garrettj403/SciencePlots#10]
Hello,
Thank you for this repo, it is amazing.
I have a question regarding the styles, say I use the ieee style to draw the graphs:
```
plt.style.use(['ieee', 'no-latex'])
plt.plot(x1,y1)
plt.plot(x2, y2)
plt.plot(x3, y3)
```

I will get the plots with three different line styles. How can I force for example `y1` and `y2 `to be drawn with the same line style but `y3` by another?
I could manually, add a linestyle attribute for each plot, but is there a way to use the previous style?

Thanks

**Comment by garrettj403** [comment]
There isn't a way to do this automatically using ``SciencePlots``, but you can always define your own style (i.e., look at how ``ieee.mplstyle`` is structured and then make your own style with whatever modifications you like).

Alternatively, you can copy the line style using:
```python
import numpy as np 
import matplotlib.pyplot as plt 
plt.style.use(['science', 'ieee', 'no-latex'])

def model(x, p):
    return x ** (2 * p + 1) / (1 + x ** (2 * p))

x = np.linspace(0.75, 1.25, 201)
y1 = model(x, 15)
y2 = model(x, 30)
y3 = model(x, 80)

fig, ax = plt.subplots()
ln1 = plt.plot(x, y1)
ln2 = plt.plot(x, y2, ls=ln1[0].get_linestyle())
ln3 = plt.plot(x, y3)
plt.autoscale(tight=True)
plt.savefig('temp.png')
```

In this plot, the first two lines will have the same line style.

I'm glad you find the package useful!

**Comment by Yoorthiziri** [comment]
Thank you, that's what I was looking for: `get_linestyle()`.
