### ISSUE TITLE
Styles not found in the style library

### ISSUE THREAD

**Issue by klezm** [garrettj403/SciencePlots#11]
If you're using IPython and import matplotlib before installing SciencePlots, the style library won't be reloaded and therefore the styles won't be found.
Without restarting the kernel you can run

```py
matplotlib.style.reload_library()
```

Maybe you could add this to setup script if running on IPython?

**Comment by garrettj403** [comment]
Unfortunately, adding ``plt.style.reload_library()`` to ``setup.py`` didn't help.

You will still need to use ``plt.style.reload_library()`` in IPython.

I've added this information to README (under the [FAQ header](https://github.com/garrettj403/SciencePlots#FAQ)).
