### ISSUE TITLE
Is it possible to get a style for subplots? 

### ISSUE THREAD

**Issue by alexlib** [garrettj403/SciencePlots#116]
The style looks great for a single axis plot, thanks. However, what shall be done for the subplots figure - to increase the figure size double in one direction?

**Comment by echedey-ls** [comment]
Set the figure size after appying the style. The Matplotlib documentation should have enough information on it; if not, someone at stackoverflow surely has had the same question.

SciencePlots' science style only sets a default size, you can change that afterwards.
________________________________
From: Alex Liberzon ***@***.***>
Sent: Sunday, April 21, 2024 7:35:53 PM
To: garrettj403/SciencePlots ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [garrettj403/SciencePlots] Is it possible to get a style for subplots? (Issue #116)


The style looks great for a single axis plot, thanks. However, what shall be done for the subplots figure - to increase the figure size double in one direction?

**Comment by alexlib** [comment]
What about the font size for multiple subplots figures?

**Comment by echedey-ls** [comment]
Please, read Matplotlib's documentation or find tutorials on the internet. These issues have nothing to do with SciencePlots.

https://matplotlib.org/stable/api/text_api.html#matplotlib.text.Text.set_fontsize

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.text.html

Use the kwarg fontsize
