### ISSUE TITLE
Greater symbol is not displayed correctly.

### ISSUE THREAD

**Issue by davidzanger** [garrettj403/SciencePlots#118]
### Environment

```Python console
System: Windows-10-10.0.19045-SP0
Python: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:29:11) [MSC v.1935 64 bit (AMD64)]
SciencePlots: 2.1.1
Matplotlib: 3.8.0
LaTeX distro: This is pdfTeX, Version 3.141592653-2.6-1.40.25 (MiKTeX 23.5) (preloaded format=latex.fmt)
 restricted \write18 enabled.
```

### Affected styles

```Python console
["science"]
```

### Describe the issue here

When trying to display the greater symbol in the legend, it is not displayed correctly. 

### How can we replicate it? What have you tried? Please, add a reproducible example

Here is a minimal example:
```python
    import scienceplots
    import matplotlib.pyplot as plt
    plt.style.use('science')
    plt.plot(1, 2, label='>test')
    plt.legend()
    plt.show()
   ```
Output is:
![grafik](https://github.com/garrettj403/SciencePlots/assets/54279486/b961f51b-8f40-426d-be2a-94349c73f3aa)

**Comment by echedey-ls** [comment]
Yeah, that's because you are using latex and supporting those glyphs depends on encoding/font.

https://tex.stackexchange.com/questions/2369/why-do-the-less-than-symbol-and-the-greater-than-symbol-appear-wrong-as

The following code works, with the latex commands instead. Note it is enclosed in a raw string.
```python
import scienceplots
import matplotlib.pyplot as plt
plt.style.use('science')
plt.plot(1, 2, label=r'>test \textgreater \textless')
plt.legend()
plt.show()
```
