### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by ddjhpxs** [garrettj403/SciencePlots#12]
I can correctly run "plt.style.use('science')", but then, when I plot something, some error went out："RuntimeError: Failed to process string with tex because latex could not be found"
how can I fix it? thanks!

**Comment by garrettj403** [comment]
``SciencePlots`` uses Latex for font rendering. If you don't have Latex on your computer, you can disable Latex using:
```python
plt.style.use(['science', 'no-latex'])
```
