### ISSUE TITLE
What to change in the setup to find new styles

### ISSUE THREAD

**Issue by IchBinGROOT** [garrettj403/SciencePlots#120]
### Environment

```Python console
System: Windows-10-10.0.19045-SP0
Python: 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)]
SciencePlots: 2.1.2
Matplotlib: 3.8.4
LaTeX distro:pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023)
kpathsea version 6.3.5
Copyright 2023 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.39; using libpng 1.6.39
Compiled with zlib 1.2.13; using zlib 1.2.13
Compiled with xpdf version 4.04
```

### Affected styles

```Python console
None used
```

### Describe the issue here

I found myself in the position that I need more colors than any of the proposed color cyclers have. Thus I created all 23 discrete rainbow color styles proposed by Paul Tol and put them into a subfolder ``scienceplots\styles\color\discrete-rainbow``. When I now change the version to 2.1.2 in the setup and install using ``pip install -e .`` I can only see the styles that were present before but not the new ones. What do I need to change so that they are found? 
I'd happily open a pull request afterwards because I think that many people could use the colors sometimes and I now have done the work to create all style files.

### How can we replicate it? What have you tried? Please, add a reproducible example

I have tried changing the package data to have one more layer of recursive search like this
```python
    install_requires=['matplotlib'],
    packages=["scienceplots"],
    package_data={
      'scienceplots': ['styles/**/**/*.mplstyle'],
    },
```
and like this the old ones are still found, but my new ones are not.

**Comment by IchBinGROOT** [comment]
I actually made it work in a similar way and now have it including updated changelog in a private repository. I made two commits, one where I have the script that generates the styles, edited the init and the setup, and the second one where I remove the script, and edited the change log as version 2.1.3. Do you want me to file a pull request?

**Comment by echedey-ls** [comment]
A pull request is welcome, of course!

The only necessary changes are the styles and the changelog entry.
