### ISSUE TITLE
plt.style.use("science") error on linux

### ISSUE THREAD

**Issue by cccchou** [garrettj403/SciencePlots#124]
when i use plt.style.use("science"),it shows:PermissionError: [Errno 13] Permission denied: 'latex',how can i fix it?

**Comment by echedey-ls** [comment]
Please take the time to fill out the template, so it's easier to replicate your error. Maybe you can start by checking  if latex is installed by running that command through the command line of your OS.

I will close this issue in a week if you don't provide the context.

**Comment by echedey-ls** [comment]
Closing due to lack of context provided by the user.
