### ISSUE TITLE
Change default param

### ISSUE THREAD

**Issue by kusaleev** [garrettj403/SciencePlots#14]
Hi, @garrettj403 !

I have some question: can i use my custom plotting params instead of plotting params in `science.mplstyle`?
i.e.

```python
plt.style.use(['science'])

plt.subplots_adjust(
    left=0.04,
    bottom=0.08,
    right=0.98,
    top=0.9,
    wspace=0.16,
    hspace=0.27
)
```

or not?

Default image size in `science.mplstyle` very small:)

Sincerely yours, Kirill

**Comment by kusaleev** [comment]
hm, i think i find answer:
i can change and configure params in `science.mplstyle`

```python
import matplotlib
print(matplotlib.get_configdir())
```

**Comment by garrettj403** [comment]
Hi @kusaleev, the file found at ``~/.matplotlib/stylelib/science.mplstyle`` will be overwritten if you ever update SciencePlots. I'd recommend writing your own ``*.mplstyle`` file to adjust only the parameters that you don't like in ``science``. You can then call:
```python
plt.style.use(['science', 'mystyle'])
```
This way, you'll still be using ``science.mplstyle`` and you can continue to update your installation in the future, but you can also adjust some of the parameters to your liking.

**Comment by kusaleev** [comment]
@garrettj403 thx!
