### ISSUE TITLE
Disabling (or adjusting) border ticks

### ISSUE THREAD

**Issue by maichmueller** [garrettj403/SciencePlots#17]
Hey,

first of: thanks for the great styles!
I would however like to disable (or adjust if possible) the ticks the style draws on the borders of a plot. Specifically, when I'm building a subplot figure with a big figure around it to easily have a shared x, and y label, as well as legend, then the border ticks of the invisible frame stay visible.
The following code should showcase the problem:

```
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

plt.style.use("science")
fig, axes = plt.subplots(5,2, figsize=(8,6), sharex=True, sharey=True)
axes = axes.flatten()
big = fig.add_subplot(111, frameon=False)
plt.tick_params(labelcolor='none', top=False, bottom=False, left=False, right=False)

for ax in axes:
    ax.hist(
        np.random.normal(size=10000) + np.random.randint(0,10),
        density=True,
        bins=200,
    )

plt.show()
```

Note how the ticks are even plotted between two subplots in the whitespace. If you know how to selectively disable this, it would be appreciated.

Best regards,
Michael

**Comment by garrettj403** [comment]
For your example, you just need to get rid of the ticks by setting: ``ax.set_xticks([], [])``

Here's the correct code:

```python
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

plt.style.use("science")

fig, axes = plt.subplots(5,2, figsize=(8,6), sharex=True, sharey=True)

big = fig.add_subplot(111, frameon=False)
big.set_xticks([], [])
big.set_yticks([], [])

axes = axes.flatten()
for ax in axes:
    ax.hist(
        np.random.normal(size=10000) + np.random.randint(0,10),
        density=True,
        bins=200,
    )

plt.show()

```
