### ISSUE TITLE
Cannot find latex

### ISSUE THREAD

**Issue by dzqann** [garrettj403/SciencePlots#18]
When I run the demo, there has been an error called: RuntimeError: Failed to process string with tex because latex could not be found

**Comment by garrettj403** [comment]
This is answered in the [FAQ](https://github.com/garrettj403/SciencePlots#faq).

**Comment by RafalKucharskiPK** [comment]
I am afraid this is not really answered. Not in detail, at least for macOS. 
I have tex, I can call `which latex` from terminal and receive path, but still I get this error.
Please provide some background on installation, maybe refer to troubleshooting for matplotlib, or suggest dependencies? Thanks!

**Comment by garrettj403** [comment]
Hi @RafalKucharskiPK 

Sorry for the delay. I'm glad that you were able to figure it out.

I've added a bit more information to the README (listed under ["Installing Latex"](https://github.com/garrettj403/SciencePlots#installing-latex)).

**Comment by ZhongyuXu** [comment]
> I am afraid this is not really answered. Not in detail, at least for macOS. I have tex, I can call `which latex` from terminal and receive path, but still I get this error. Please provide some background on installation, maybe refer to troubleshooting for matplotlib, or suggest dependencies? Thanks!
> 
> Edit: After two hours I found a way and:
> 
> 1. Reinstalled MacTex
> 2. made sure it is in `which latex`
> 3. added latex binary to python path: os.environ["PATH"] += os.pathsep + '/Library/TeX/texbin'
> 4. and only then it worked,
> 
> great package btw

Thank you so much. Your third suggestion saved my life.
