### ISSUE TITLE
Why not Times New Roman font?

### ISSUE THREAD

**Issue by ouening** [garrettj403/SciencePlots#25]
Hi, I see many figures use Times New Roman font as default. Why don't you use it? If I want, how could I change the code? Thank you!

**Comment by garrettj403** [comment]
I'm not too sure what you mean... but the font is set on [line 41 of ``science.mplstyle``](https://github.com/garrettj403/SciencePlots/blob/a81dd3a8871de45b5a9ea12bb299e3cdb94f7146/styles/science.mplstyle#L41):

```
# Use serif fonts
font.serif : Times New Roman
font.family : serif
mathtext.fontset : dejavuserif
```
You can overwrite this however you like.

**Comment by ouening** [comment]
I have figured out why the font is not Times New Roman. In [https://matplotlib.org/3.1.1/tutorials/text/usetex.html](https://matplotlib.org/3.1.1/tutorials/text/usetex.html), the example is 
```
font.family        : serif
font.serif         : Times, Palatino, New Century Schoolbook, Bookman, Computer Modern Roman
font.sans-serif    : Helvetica, Avant Garde, Computer Modern Sans serif
font.cursive       : Zapf Chancery
font.monospace     : Courier, Computer Modern Typewriter

text.usetex        : true
```
So I update the code like:
```
plt.style.use(['science','ieee'])
plt.rcParams.update({
    "legend.fancybox": False,
    "legend.frameon": False,
    "text.usetex": True,
    "font.family": "serif",
    "font.serif": ["Times"],
    "font.size":11})
```
Result is:

![a](https://user-images.githubusercontent.com/15122811/97125868-33564580-1770-11eb-8925-8f03f941ef46.png)

If not, the result is:
![image](https://user-images.githubusercontent.com/15122811/97125905-49fc9c80-1770-11eb-88a8-9aab7afd70e3.png)

**Comment by garrettj403** [comment]
Hi @ouening 

Sorry for the long delay. I tried switching to the ``Times`` font, but then the special math characters fail to render in the PDFs. For example, ``ax.set_ylabel='Current ($\mu$A)'`` results in:

![fig2-error](https://user-images.githubusercontent.com/14835953/100635008-fb599980-32fd-11eb-87df-4fdc327500c5.jpg)

This previously worked fine, so for now I'll leave the SciencePlots font as the default serif font until I figure out what is wrong. 

Note: For the ``ieee`` style, I changed the default font to ``Times`` (see commit b0de4cafe5bd5e2d2764b8eb7febd4141b095923). To get this to work however, I had to change the y-axis label to: ``ax.set_ylabel='Current (\textmu A)'``.

**Comment by garrettj403** [comment]
Note: I changed the default font in ``ieee`` to ``Times`` in commit b0de4cafe5bd5e2d2764b8eb7febd4141b095923 (since IEEE papers use Times New Roman).

**Comment by JBorrow** [comment]
As a note you may wish to use the STIX fonts that look very similar to Times but are fully open. The problem with math rendering is that the usual Times font does not include all the required glyphs.

**Comment by echedey-ls** [comment]
Since STIX fonts have been included in `science` and `ieee` styles, I'm closing this.

Thanks JBorrow!
