### ISSUE TITLE
missing font metrics file: cmr10

### ISSUE THREAD

**Issue by ztz1995** [garrettj403/SciencePlots#26]
I installed this package with pip on a centos system.
An error occured:
**_"FileNotFoundError: missing font metrics file: cmr10"_**
Then, I installed cmr10.ttf no my computer, but nothing changed.
How can I fix this error? Thanks!

**Comment by garrettj403** [comment]
I'm not too sure... I don't use CentOS, but it is likely an issue with your Latex installation.

Does this help?

https://tex.stackexchange.com/questions/442179/why-are-tfm-files-missing-in-the-latex-rsfs-package

**Comment by ztz1995** [comment]
> I'm not too sure... I don't use CentOS, but it is likely an issue with your Latex installation.
> 
> Does this help?
> 
> https://tex.stackexchange.com/questions/442179/why-are-tfm-files-missing-in-the-latex-rsfs-package

With your hint, I found that there was someting wrong with my environment variables.
After corrected them, the program runs perfectly.
Thank you very much!

**Comment by LukasK13** [comment]
Hi @garrettj403 ,
I'm having the same problem, can you provide some more information on how you fixed the problem?

**Comment by garrettj403** [comment]
I don't have a CentOS system, but @ztz1995 may be able to help. 

@ztz1995, can you tell us what you did to fix this issue?

**Comment by LukasK13** [comment]
I'm sorry, of course I meant to tag @ztz1995 .

**Comment by ztz1995** [comment]
> I'm sorry, of course I meant to tag @ztz1995 .

The latex I use is texlive2020.
I fixed this issue by adding these lines to ~/.bashrc
```
export MANPATH=/urs/local/texlive/2020/texmf-dist/doc/man:${MANPATH}
export INFOPATH=/usr/local/texlive/2020/texmf-dist/doc/info:${INFOPATH}
export PATH=/usr/local/texlive/2020/bin/x86_64-linux:${PATH}
```
Don't forget to 
`source ~/.bashrc`

**Comment by LukasK13** [comment]
Thank you very much.

Adding
```export PATH=/usr/local/texlive/2020/bin/x86_64-darwin:${PATH}```
to `~/.zprofile` fixed it for me on MacOS Big Sur.
