### ISSUE TITLE
Use SciencePlots in Google Colab

### ISSUE THREAD

**Issue by JulianCologne** [garrettj403/SciencePlots#28]
I was trying to get this to work in Google Colab for some hours until I found the solution.
Unlike the desktop you have to reload the style libraries to recognize and use the new *.mplstyle files.
```
!pip install SciencePlots
import matplotlib.pyplot as plt
plt.style.reload_library() # <<<<<<<<<<
plt.style.use(['science', 'no-latex'])
```
Maybe you can add this in the README under Installation if someone else wants to use SciencePlots in Google Colab and encounters the problem.
Thanks! Great library!

**Comment by garrettj403** [comment]
Hi @JulianCologne 

Thank you for pointing that out. I've added that information to the README (under the FAQ section). 

Cheers!

**Comment by garrettj403** [comment]
Addressed in commit bd677fdebaec8c4ae49a422ad5a4c90328a4f069

**Comment by garrettj403** [comment]
I've also added ``matplotlib.style.reload_library()`` to the end of the installation function in ``setup.py`` (see commit 657b860).

**Comment by garrettj403** [comment]
Unfortunately, ``plt.style.reload_library()`` doesn't seem to help at all when it is added to ``setup.py``.

You will still need to use ``plt.style.reload_library()`` in your Google Colab document.
