### ISSUE TITLE
Grid below graph

### ISSUE THREAD

**Issue by AlexanderVanUffelen** [garrettj403/SciencePlots#34]
Currently the grid is plotted on top of the graph:
![image](https://user-images.githubusercontent.com/49979885/111538430-f6b1d780-876c-11eb-907c-8e9749960ace.png)
It looks cleaner if the grid is below the graph:
![image](https://user-images.githubusercontent.com/49979885/111538622-3678bf00-876d-11eb-8833-e167a1c2c1af.png)
This can be done by adding `axes.axisbelow : True` to the grid.mplstyle

**Comment by garrettj403** [comment]
Hi @AlexanderVanUffelen 

Thank you for pointing this out.

Seems like it only affected what Matplotlib calls "patches" (including bar graphs like your example). Line plots were still plotted above the grid lines.

From the Matplotlib webpage:
```python
#axes.axisbelow      : line    ## draw axis gridlines and ticks below
                               ## patches (True); above patches but below
                               ## lines ('line'); or above all (False)
```

Anyway, I added ``axes.axisbelow : True`` to ``grid.mplstyle`` in commit 27ed271
