### ISSUE TITLE
Creating grids and grey background on google colab

### ISSUE THREAD

**Issue by fc0712** [garrettj403/SciencePlots#36]
Hey.

I was using your package to create graphs for master thesis and has encountered some issues.

The figures doesn't seem to be created with the same layout as shown on the readme and in the examples.

I have imported the library and used the reload command. 

I have used the following script to create a duplicate of the examples:

`def model(x, p):
    return x ** (2 * p + 1) / (1 + x ** (2 * p))

pparam = dict(xlabel='Voltage (mV)', ylabel='Current ($\mu$A)')

x = np.linspace(0.75, 1.25, 201)

with plt.style.context(['science']):
    fig, ax = plt.subplots()
    for p in [10, 15, 20, 30, 50, 100]:
        ax.plot(x, model(x, p), label=p)
    ax.legend(title='Order')
    ax.autoscale(tight=True)
    ax.set(**pparam)
    fig.savefig('fig1.jpeg',dpi=300)`

![fig1](https://user-images.githubusercontent.com/25506722/113501893-df266d00-9528-11eb-8c70-cdd04b14829b.jpeg)

**Comment by garrettj403** [comment]
Hi @fc0712, did you import the ``seaborn`` package in this example?

Could you send the entire script that you use (including import statements)?

**Comment by fwmeng88** [comment]
Following up this example, how we can use `seaborn` along with `SciencePlots`? A minimum example would be appreciated. 

Thank you! @garrettj403
