### ISSUE TITLE
Failed to process string with tex because latex could not be found

### ISSUE THREAD

**Issue by inkplatform** [garrettj403/SciencePlots#37]
Hi, I'm using it in Ubuntu 18.04, but I keep getting this error. Can you tell me why this is this? How can I fix it?

RuntimeError: Failed to process string with tex because latex could not be found

**Comment by garrettj403** [comment]
You need LaTeX on your machine to use SciencePlots. See 1 in the [FAQ](https://github.com/garrettj403/SciencePlots#faq)
