### ISSUE TITLE
Adding LaTeX packages for additional symbols to avoid process error

### ISSUE THREAD

**Issue by haltugyildirim** [garrettj403/SciencePlots#39]
Hi.

This issue is already solved for me, but I wanted to share if somebody else comes across with it. I had a problem with symbols \circlearrowright & \circlearrowleft that I am using in a label. LaTeX was not able to process the string. Turns out that this symbols are under \usepackage{ amssymb }. So I needed to add this package to *.mplstyle under the folder _"user\.matplotlib\stylelib"_ as;

```
text.latex.preamble : \usepackage{amsmath} \usepackage{ amssymb }
```

Best,
Altug

**Comment by garrettj403** [comment]
Thanks for the tip!

I've added `amssymb` in 82193ee.
