### ISSUE TITLE
"Science" style not found on Google Colab

### ISSUE THREAD

**Issue by rish-16** [garrettj403/SciencePlots#40]
Hey there!

Thanks for the amazing project! Really useful for upcoming submissions 😅 

Though, I ran into an issue when trying it out on Google Colab. I `pip` installed the style library following the instructions on the `README`. I then wrote down 

```python
import matplotlib.pyplot as plt

plt.style.use(['science','ieee'])
```

and it gave me the following error:
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/matplotlib/style/core.py in use(style)
    113             try:
--> 114                 rc = rc_params_from_file(style, use_default_template=False)
    115                 _apply_style(rc)

5 frames
FileNotFoundError: [Errno 2] No such file or directory: 'science'

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/matplotlib/style/core.py in use(style)
    118                     "{!r} not found in the style library and input is not a "
    119                     "valid URL or path; see `style.available` for list of "
--> 120                     "available styles".format(style))
    121 
    122 

OSError: 'science' not found in the style library and input is not a valid URL or path; see `style.available` for list of available styles
```

Any remedies for this would be awesome!

Thanks :)

**Comment by garrettj403** [comment]
Hi @rish-16

Does this work?

```python
import matplotlib.pyplot as plt
plt.style.reload_library()
plt.style.use('science')
```

**Comment by rish-16** [comment]
It works now. Thank you!

**Comment by 979736316** [comment]
> 

Sorry, I tried to run the code you provided in the lab, but it failed. My version is 2.0.1. 

```
def model(x, p):
    return x ** (2 * p + 1) / (1 + x ** (2 * p))


pparam = dict(xlabel='Voltage (mV)', ylabel=r'Current ($\mu$A)')

x = np.linspace(0.75, 1.25, 201)


fig, ax = plt.subplots(figsize=[4,3],dpi=200)
for p in [10, 15, 20, 30, 50, 100]:
    ax.plot(x, model(x, p), label=p)
ax.legend(title='Order')
ax.autoscale(tight=True)
ax.set(**pparam)
# plt.style.use(['science', 'no-latex', 'high-vis'])
# matplotlib.rc('font', family='Times')
plt.style.reload_library()
plt.style.use('science')
plt.show()
```

**Comment by echedey-ls** [comment]
Did you do `import scienceplots` on top of your script? We changed how it is imported and now it is needed. 

Also, why the `plt.style.reload_library()`? If I'm not mistaken, that clears styles given to matplotlib through this new system. Remove that line. 

Tell us how it did go.

**Comment by 979736316** [comment]
> 

To run "science" style, in the Google Colab, we set the `plt.style.reload_library()`. 
The following is the code I provided to run. Please tell me what I should do to run the ”science“ style code successfully in the Google Colab.

```
import matplotlib.pyplot as plt
!pip install SciencePlots
import scienceplots
def model(x, p):
    return x ** (2 * p + 1) / (1 + x ** (2 * p))


pparam = dict(xlabel='Voltage (mV)', ylabel=r'Current ($\mu$A)')

x = np.linspace(0.75, 1.25, 201)

with plt.style.context(['science', 'high-vis']):
    fig, ax = plt.subplots(figsize=(4,3),dpi=200)
    for p in [10, 15, 20, 30, 50, 100]:
        ax.plot(x, model(x, p), label=p)
    ax.legend(title='Order')
    ax.set(xlabel='Voltage (mV)')
    ax.set(ylabel='Current ($\mu$A)')
    ax.autoscale(tight=True)
```

**Comment by echedey-ls** [comment]
@979736316 I assumed your error was the style not found, since that one is in this issue: next time, copy&paste it here in a code block. 
After a bit of testing, I believe it's not. Run the following code and tell me what error you made.
```bash
!sudo apt-get install dvipng texlive-latex-extra texlive-fonts-recommended texlive-latex-recommended cm-super
!pip install SciencePlots
```
```python
import matplotlib.pyplot as plt
import scienceplots
import numpy as np
```
```python
def model(x, p):
    return x ** (2 * p + 1) / (1 + x ** (2 * p))

pparam = dict(xlabel='Voltage (mV)', ylabel=r'Current ($\mu$A)')

x = np.linspace(0.75, 1.25, 201)

with plt.style.context(['science', 'high-vis']):
    fig, ax = plt.subplots(figsize=(4,3),dpi=200)
    for p in [10, 15, 20, 30, 50, 100]:
        ax.plot(x, model(x, p), label=p)
    ax.legend(title='Order')
    ax.set(xlabel='Voltage (mV)')
    ax.set(ylabel='Current ($\mu$A)')
    ax.autoscale(tight=True)
```

**Comment by 979736316** [comment]
> 

Thank you very much. Now, I have successfully run. But, the graphic font seems strange (as shown in Figure 1). This may be a display problem. I ran successfully on the local environment, as shown in Figure 2. We can observe that their fonts seem different.
![image](https://user-images.githubusercontent.com/52651366/207074528-19bae9ae-bba5-4bc2-b43a-614f4ec0e189.png)

![image](https://user-images.githubusercontent.com/52651366/207074613-9abbfdcc-6f42-4835-b545-74f255375425.png)

**Comment by echedey-ls** [comment]
You're welcome. Always happy to help.
Well spotted, didn't notice it.
I've opened a new issue to talk about it. Would you like to do some troubleshooting? I'm too busy these days, but I think it has to do with the area it is rendering the text. Let's talk in issue #83
Thanks for letting us know all that.

**Comment by 979736316** [comment]
Sure!
