### ISSUE TITLE
Resolution of density scatter plots

### ISSUE THREAD

**Issue by ayylemao** [garrettj403/SciencePlots#42]
Is there an option to keep the original scatter resolution obtainable without setting the plt style to 'science'?

![Plot without science style disabled, high resolution in the scatter density plot](https://user-images.githubusercontent.com/60004995/122201859-c299a000-ce9c-11eb-8ac0-1644eaa90fa9.png)
_-Plot without science style disabled, high resolution in the scatter density plot_
![Same plot with science style enabled, notice low resolution in scatter density plot, especialy visible in top left corner region.](https://user-images.githubusercontent.com/60004995/122201915-d0e7bc00-ce9c-11eb-9e1f-ba89f3971b86.png)
_-Same plot with science style enabled, notice low resolution in scatter density plot, especialy visible in top left corner region._

Options Used for plotting:
plt.style.use(['science','ieee', 'scatter'])

**Comment by garrettj403** [comment]
Hi @ayylemao 

Nothing that I know of in the [`science`](https://github.com/garrettj403/SciencePlots/blob/master/styles/science.mplstyle) style should cause this... if you like, you can add the different parameters to the top of your Python script and try commenting/uncommenting to find the culprit:

```python
import matplotlib as mpl
from cycler import cycler

mpl.rcParams['axes.prop_cycle'] = cycler(color=['0C5DA5', '00B945', 'FF9500', 'FF2C00', '845B97', '474747', '9e9e9e'])

mpl.rcParams['figure.figsize'] = (3.5, 2.625)

# etc
```

Also try saving with different figure sizes and different files types (png vs jpg vs pdf). You can also try disabling Latex using the `no-latex` style to see if that changes anything.
