### ISSUE TITLE
[compatibility]Install from pypi broken down in python 3.9

### ISSUE THREAD

**Issue by whbjzzwjxq** [garrettj403/SciencePlots#47]
When I installed SciencePlots from pypi, pip would throw out this error:
```python
ModuleNotFoundError: No module named '_ctypes'.
```
And after installing SciencePlots, matplotlib would throw out this error:
```python
OSError: 'ieee' not found in the style library and input is not a valid URL or path
```

**Comment by garrettj403** [comment]
Hey, sorry it took a while to get back to you.

Does it work with this?
```bash
pip install git+https://github.com/garrettj403/SciencePlots
```

**Comment by garrettj403** [comment]
Hey, sorry it took a while to get back to you.

I made a couple changes to the setup script. Can you try to install the latest version?
```bash
pip install SciencePlots==1.0.9
```

**Comment by whbjzzwjxq** [comment]
It is OK now, Thanks.
