### ISSUE TITLE
Special characters are not showing in X or Y axis  

### ISSUE THREAD

**Issue by karimmd** [garrettj403/SciencePlots#52]
In the code I defined:
plt.ylabel('Trusted Nodes (%)')
But in the plot, It's not showing the % sign, Instead showing Trusted Nodes ( . I think same issue happens with some other sign like #,$.
Uing the default Matplotlib theme, these signs are easily viewable in the X or Y axis depending on how you define in the code.

**Comment by garrettj403** [comment]
It should work if you precede it with a ``\`` (escape character).

I.e., ``plt.ylabel('Trusted Nodes (\%)')``
