### ISSUE TITLE
Installation behind proxy not working.

### ISSUE THREAD

**Issue by Pleuel** [garrettj403/SciencePlots#54]
I am trying to install SciencePlots behind a proxy using pip.
`pip install SciencePlots  --proxy http://proxy-ip:port`
While the package download is working correctly, I encountered the following Error during the installation procedure:
```
Running command pip subprocess to install build dependencies
Using pip 22.0.3 from C:\Users\Username\AppData\Local\Temp\pip-standalone-pip-_nduq2qr\__env_pip__.zip\pip (python 3.9)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002902A131340>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
```
To me it seems like the proxy is somehow not consequently used. Is there a way to fix this?

**Comment by garrettj403** [comment]
Hi @Pleuel 

Sorry -- I don't have any experience with this. Let me know if you find a way to get it working!

**Comment by thu-bear** [comment]
> I am trying to install SciencePlots behind a proxy using pip. `pip install SciencePlots --proxy http://proxy-ip:port` While the package download is working correctly, I encountered the following Error during the installation procedure:
> 
> ```
> Running command pip subprocess to install build dependencies
> Using pip 22.0.3 from C:\Users\Username\AppData\Local\Temp\pip-standalone-pip-_nduq2qr\__env_pip__.zip\pip (python 3.9)
> WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002902A131340>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
> ```
> 
> To me it seems like the proxy is somehow not consequently used. Is there a way to fix this?

I also had this problem in version 1.0.9, however it didn't happen in previous versions. This seems to be related to setuptools related changes in 1.0.9.
`pip install SciencePlots==1.0.8 --proxy http://proxy-ip:port`

**Comment by echedey-ls** [comment]
I will close this issue due to inactivity. I haven't tried to reproduce it, but looks more a problem with pip more than SciencePlots.
If it persists, and can be isolated to this package (I mean, running `pip install --force-reinstall numpy --proxy http://proxy-ip:port` does not raise errors, but `pip install --force-reinstall SciencePlots --proxy http://proxy-ip:port` does), let us know. We will kindly try to help.
