### ISSUE TITLE
Figure size for IEEE not setting correctly

### ISSUE THREAD

**Issue by HalonMallic** [garrettj403/SciencePlots#55]
I have been using this library to make some plots for use in IEEE papers.

When using `plt.style.use(['science','ieee'])` and `fig.savefig('Figures/tradeproportion_orders.pdf')` I find that the output is larger than a single IEEE column width.

Do you know why this is/ how to fix it?

**Comment by garrettj403** [comment]
Hi Billy

It's hard to say without seeing your Python script / latex document.

Do you import any other packages that might change the default figure size (e.g., seaborn)? I assume that you aren't changing the figure size manually in either the Python script (e.g., something like ``plt.figure(figsize=(5,5))``) or the Latex document (e.g., something like ``\includegraphics[width=\textwidth]{figure.pdf}``).

The column width in IEEE journals is 3.5 inches. The ``ieee.mplstyle`` style sets the width to 3.3 inches.

**Comment by HalonMallic** [comment]
Thanks very much - I've found that when the figure is saved, it gets saved as the correct figure size.  It's only when using plt.show() that the size is incorrect!
