### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by YasLbk** [garrettj403/SciencePlots#57]
In "Installing SciencePlots manually", it seems to me that the command 

`cp styles/*/*.mplstyle ~/.matplotlib/stylelib/`

is not sufficient because it doesn't copy the style-files that aren't in a directory and that are saved directy in "styles/". Which makes compilation fails because files are missing (science.mplstyle).  

It seems to me that you have to add the command 
`cp styles/*/*.mplstyle ~/.matplotlib/stylelib/  && cp *.mplstyle ~/.matplotlib/stylelib/ `

**Comment by garrettj403** [comment]
Thanks for pointing this out. I fixed the [Wiki](https://github.com/garrettj403/SciencePlots/wiki/FAQ#installing-scienceplots-manually).
