### ISSUE TITLE
Plotting will take a long time

### ISSUE THREAD

**Issue by Peng-YM** [garrettj403/SciencePlots#6]
When I use this style, I find it takes a very long time (more than 20 seconds in my i7 computer) to plot even a small figure. I think the possible reason is the latex postprocessing procedure. Do you have any idea to reduce the plotting time? Thank you in advance!

**Comment by garrettj403** [comment]
You can try disabling Latex by using:

```python
import matplotlib.pyplot as plt 
plt.style.use(['science', 'no-latex'])
```

Does that help?

**Comment by s1291** [comment]
@garrettj403 
I had the same issue, Latex rendering is slow, why not use[ mathtex](https://matplotlib.org/3.2.1/tutorials/text/mathtext.html)t instead?

* Could you please that (I mean `no-latex`) to the main README.md?

**Comment by Peng-YM** [comment]
> You can try disabling Latex by using:
> 
> ```python
> import matplotlib.pyplot as plt 
> plt.style.use(['science', 'no-latex'])
> ```
> 
> Does that help?

Plotting with `no-latex` style is much faster than before. **However, the font style of labels and legends are inconsistent.**  For example:

### 1. With LaTeX
```python
import matplotlib.pyplot as plt
import numpy as np
plt.style.use(['science', 'ieee'])
X = np.linspace(0, 2*np.pi)
plt.plot(X, np.sin(X), label=r'$f_1=sin(x)$')
plt.plot(X, np.cos(X), label=r'$f_2=cos(x)$')
plt.xlabel(r'$x$')
plt.ylabel(r'$f$')
plt.legend()
```
![latex](https://user-images.githubusercontent.com/21050064/80269045-f9cc5100-86de-11ea-8ad3-12fd3d42669f.png)
### 2. No LaTeX
```python
import matplotlib.pyplot as plt
import numpy as np
plt.style.use(['science', 'ieee', 'no-latex'])
X = np.linspace(0, 2*np.pi)
plt.plot(X, np.sin(X), label=r'$f_1=sin(x)$')
plt.plot(X, np.cos(X), label=r'$f_2=cos(x)$')
plt.xlabel(r'$x$')
plt.ylabel(r'$f$')
plt.legend()
```
![nolatex](https://user-images.githubusercontent.com/21050064/80269079-38620b80-86df-11ea-861e-d9cddfee4379.png)

As you can see, the legend and x, y-axis still have the default font style.

**Comment by garrettj403** [comment]
> Latex rendering is slow, why not use mathtext instead

I find the font rendering with Latex more appealing than plain MathText. If you want to use MathText instead, just disable Latex using ``no-latex``. On my computer (a 2019 13" MacBook Pro), it takes 0.77s to generate [this figure](https://raw.githubusercontent.com/garrettj403/SciencePlots/master/examples/figures/fig1.jpg) with Latex and 0.43s without Latex.

> Could you please add that (I mean no-latex) to the main README.md?

I added a FAQ to the README [here](https://github.com/garrettj403/SciencePlots#faq) and I describe how to disable Latex.

> Plotting with no-latex style is much faster than before. However, the font style of labels and legends are inconsistent.

I added [a new line](https://github.com/garrettj403/SciencePlots/blob/efa5da4c53798ede2528074a9ed4eac800603998/styles/science.mplstyle#L42) to the ``science`` style to make MathText use a serif font.
