### ISSUE TITLE
Use setup.py build system

### ISSUE THREAD

**Issue by anjandev** [garrettj403/SciencePlots#61]
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/34969#note_239417

**Comment by echedey-ls** [comment]
I've made a PR where I changed the distribution model. Right now I believe it should be fixed for you, but it means using my repo until it gets merged, if it does.
Of course, I understand you don't want an unofficial distribution on your system, but even if you didn't, I'd like to know if it solves your problem to continue working on docs, tests and doing tweaks. TIA.

Hope it helps. All input is welcome.
