### ISSUE TITLE
Figure size cannot be fixed.

### ISSUE THREAD

**Issue by Eureka-0** [garrettj403/SciencePlots#63]
Hi, I'm using SciencePlots like this:

`plt.style.use("science")`

Before plotting I set the figure size to A4(8.3x11.7). But after saving it to .jpg, the figure size changed adapting to chart size. Is there any way to fix the figure size?

**Comment by garrettj403** [comment]
Hi @Eureka-0 

You want a figure to be the full size of a piece of A4 paper? This code does that:
```python
import matplotlib.pyplot as plt
plt.style.use('science')
plt.figure(figsize=(11.7, 8.3))
plt.plot([1, 2, 3], [2, 1, 3], 'r^--')
plt.plot([1, 2, 3], [3, 1, 2], 'bv--')
plt.xlabel("$x$-axis label")
plt.ylabel("$y$-axis label")
plt.tight_layout()
plt.savefig("test.jpg")
```
This gives me a figure with dimensions 11.7" x 8.1" (A4 in landscape).
![test](https://user-images.githubusercontent.com/14835953/176511011-6e8ff984-815b-4b6c-8bd7-526cad4738bb.jpg)
