### ISSUE TITLE
Times New Roman: Bad looking plus/minus sign.

### ISSUE THREAD

**Issue by leo-hstone** [garrettj403/SciencePlots#67]
![image](https://user-images.githubusercontent.com/62036826/180428243-64d0a870-c956-4491-8b7e-efa06cb66551.png)

The plus and minus signs are somehow shifted downwards. It would be awesome if anyone could reproduce this and/or knows how to fix it!

**Comment by echedey-ls** [comment]
Hi!
I haven't found a right way of solving that, but two notes:
* See this [StackOverflow ](url) thread about the minus sign.
* See this [matplotlib docs ](https://matplotlib.org/stable/tutorials/text/usetex.html) about Latex and changing the font
  For the latter, you'll make use of rcParams. See following code:
```
import matplotlib.pyplot as plt
import matplotlib
import pandas as pd

data = pd.DataFrame(zip([0, 2, 4],[1, 3, 5]), columns=[r'+0',r'-8'])

plt.style.use(['science'])
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'Courier'  # This is a monospace font. See more at https://matplotlib.org/stable/tutorials/text/usetex.html

data.plot()
plt.show()
```
