### ISSUE TITLE
science + grid not working 

### ISSUE THREAD

**Issue by kanginthaya** [garrettj403/SciencePlots#7]
Hi,

Great package, I am using this for my master thesis. It's just fantastic to use. Just a small problem however - 
`plt.style.use(['science','grid'])` seems not to work for me. Any suggestions on how to get it working?

**Comment by kanginthaya** [comment]
I fixed it by alternately using -

`ax.grid(linestyle='--', alpha=0.5)`

**Comment by xuehuachunsheng** [comment]
It seems that the legend part without grid.

**Comment by xuehuachunsheng** [comment]
The latest commit provide the ['science', 'grid'] support. Please use the latest commit.
