### ISSUE TITLE
Is Latex necessary?

### ISSUE THREAD

**Issue by danishTUE** [garrettj403/SciencePlots#70]
Hi,

Just came across this library and found it interesting. However, I dont use Latex. Can this be used only in relation with Latex? or can it be used stand-alone as well for generating the charts.

Regards,

Danish

**Comment by echedey-ls** [comment]
There's a style for that, `no-latex` [This file](https://github.com/garrettj403/SciencePlots/blob/master/styles/misc/no-latex.mplstyle). You can also change the rcParams with the file content.

You won't be able to use the equation markup of latex on the labels, tho.
