### ISSUE TITLE
Install names mismatch in v1.1.0

### ISSUE THREAD

**Issue by alexfikl** [garrettj403/SciencePlots#74]
In version 1.1.0 the import names were changed to `scienceplots` (lowercase) but the folder name / repo name / pypi name are still `SciencePlots` (camelcase). For a simple reproducer, clone the repo and run
```
python -m pip install -e .
```
which gives 
```
error: package directory 'scienceplots' does not exist
```
due to https://github.com/garrettj403/SciencePlots/blob/6545c7227aaa10291933365f875e2698f14558ed/setup.py#L28

The Arch package is working around it too
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-scienceplots#n20

**Comment by echedey-ls** [comment]
Thanks for letting us know. Will fix that ASAP.
Can be reproduced on linux-based OSs. Not on Windows.

**Comment by alexfikl** [comment]
> Thanks for letting us know. Will fix that ASAP. Can be reproduced on linux-based OSs. Not on Windows.

Thanks for the quick response! 
On Windows it probably has something to do with case sensitive file systems?

**Comment by echedey-ls** [comment]
> On Windows it probably has something to do with case insensitive file systems?

Was definitely that. Sorry for not testing on Linux.

**Comment by echedey-ls** [comment]
Reopening because github doesn't show git rename change.

**Comment by echedey-ls** [comment]
Didn't expect renaming to be this difficult. Solved.

Thanks for your help.
