### ISSUE TITLE
Google Colab: Problem rendering text in all text items

### ISSUE THREAD

**Issue by echedey-ls** [garrettj403/SciencePlots#83]
Moving here conversation from #40 
It sure has nothing to do with SciencePlots, but until further info is gathered, we will discuss it here.

On 2022-12-12, this comment was made:
> The graphic font seems strange (as shown in Figure 1). This may be a display problem. I ran successfully on the local environment, as shown in Figure 2. We can observe that their fonts seem different.
> ![](https://user-images.githubusercontent.com/52651366/207074528-19bae9ae-bba5-4bc2-b43a-614f4ec0e189.png)
> ![](https://user-images.githubusercontent.com/52651366/207074613-9abbfdcc-6f42-4835-b545-74f255375425.png)

**Comment by 979736316** [comment]
It is worth noting that in the google colab, the scienceplots version is 2.0.1, while it is 1.0.8 in the local environment.

**Comment by ttesileanu** [comment]
This seems to work fine in the current version of Google Colab:
<img width="728" alt="Screenshot 2023-05-03 at 10 53 02 AM" src="https://user-images.githubusercontent.com/15861465/235954047-b0d79856-9800-432d-8894-b5bcf376dccf.png">

For reference, this is the exact notebook I ran:
<img width="767" alt="Screenshot 2023-05-03 at 10 55 30 AM" src="https://user-images.githubusercontent.com/15861465/235954855-422db5c0-6113-417e-8fa3-8c90fd340fa2.png">

**Comment by echedey-ls** [comment]
@ttesileanu thank you very much for spotting that!
