### ISSUE TITLE
CJK Noto Fonts - Chinese and Korean don't work - Font 'default' does not have a glyph

### ISSUE THREAD

**Issue by downeykking** [garrettj403/SciencePlots#84]
os: ubuntu 22.04
    python: 3.9
    scienceplots: 2.0.1

After following the FAQ Installing CJK fonts, I have already installed `fonts-noto-cjk`.
But when i tried the examples like:
```python
with plt.style.context(['science', 'no-latex', 'cjk-tc-font']):
    fig, ax = plt.subplots()
    for p in [5, 7, 10, 15, 20, 30, 38, 50, 100]:
        ax.plot(x, model(x, p), label=p)
    ax.legend(title='Order', fontsize=7)
    ax.set(xlabel=r'電壓 (mV)')
    ax.set(ylabel=r'電流 ($\mu$A)')
    ax.autoscale(tight=True)
    fig.savefig('figures/fig14a.jpg', dpi=300)

with plt.style.context(['science', 'no-latex', 'cjk-sc-font']):
    fig, ax = plt.subplots()
    for p in [5, 7, 10, 15, 20, 30, 38, 50, 100]:
        ax.plot(x, model(x, p), label=p)
    ax.legend(title='Order', fontsize=7)
    ax.set(xlabel=r'电压 (mV)')
    ax.set(ylabel=r'电流 ($\mu$A)')
    ax.autoscale(tight=True)
    fig.savefig('figures/fig14b.jpg', dpi=300)

with plt.style.context(['science', 'no-latex', 'cjk-jp-font']):
    fig, ax = plt.subplots()
    for p in [5, 7, 10, 15, 20, 30, 38, 50, 100]:
        ax.plot(x, model(x, p), label=p)
    ax.legend(title='Order', fontsize=7)
    ax.set(xlabel=r'電圧 (mV)')
    ax.set(ylabel=r'電気 ($\mu$A)')
    ax.autoscale(tight=True)
    fig.savefig('figures/fig14c.jpg', dpi=300)

```
Only `cjk-jp-font` made sense.  `Noto Serif CJK SC` and `Noto Serif CJK TC` both failed.
```
findfont: Generic family 'serif' not found because none of the following families were found: Noto Serif CJK SC
findfont: Generic family 'serif' not found because none of the following families were found: Noto Serif CJK TC
```
How can I solve this problem? Thanks in advance.

**Comment by machel7** [comment]
I have same problem  in using  simplified chinese。

RuntimeWarning: Glyph 21387 missing from current font.
  font.set_text(s, 0, flags=flags)
Font 'default' does not have a glyph for '\u7535' [U+7535], substituting with a dummy symbol.
Font 'default' does not have a glyph for '\u6d41' [U+6d41], substituting with a dummy symbol.
Font 'default' does not have a glyph for '\u7535' [U+7535], substituting with a dummy symbol.
Font 'default' does not have a glyph for '\u6d41' [U+6d41], substituting with a dummy symbol.
Font 'default' does not have a glyph for '\u7535' [U+7535], substituting with a dummy symbol.
Font 'default' does not have a glyph for '\u6d41' [U+6d41], substituting with a dummy symbol.

**Comment by echedey-ls** [comment]
Hi @machel7 and @downeykking , I won't be able to troubleshoot it for some weeks due to personal constraints.
Can you two find which Latex distribution are you using (e.g. `MikTex`, `TexLive`...?
machel7, could you also please provide OS, Python version and SciencePlots version? 

Till I return, you can have a look at this [wiki entry](https://github.com/garrettj403/SciencePlots/wiki/FAQ#installing-cjk-fonts), it may hint you in solving this issue. Have a look at the issue mentioned in the wiki, in some examples, it uses a "pgf" backend, that might solve it.

Whatever you find useful, please let us know.

**Comment by FunClip** [comment]
I encountered the same problem when using Simplified Chinese.

Finally, I used [`mplfonts`](https://github.com/Clarmy/mplfonts) as a temporary solution.


`mplfonts` is a fonts manager for matplotlib.

>    This is a python package and command line tool to manage your matplotlib fonts. You can easily resolve the "tofu" problem when plotting with CJK(Chinese, Japanese, Korean) languages.

Hope it helps!

**Comment by echedey-ls** [comment]
Hi @FunClip!

Thank you very much for letting us know! I think I will deprecate our CJK styles, as I don't have both time & motivation to try to fix that. I will update the wiki in shortly.

Again, thank you.

**Comment by jeremy-feng** [comment]
Finally it worked with CJK font! Be careful to set `"pgf.preamble"`. I use the code from [matplotlib documentation](https://matplotlib.org/stable/gallery/userdemo/pgf_preamble_sgskip.html).

```python
import matplotlib as mpl
import matplotlib.pyplot as plt
import scienceplots  # noqa: F401

plt.style.use(["science"])
mpl.use("pgf")

preamble = [
    r"\usepackage{fontspec}",
    r"\setmainfont{Hei}",
]
params = {
    "font.family": "serif",
    "text.usetex": True,
    "pgf.rcfonts": False,
    "pgf.texsystem": "xelatex",
    "pgf.preamble": "\n".join(
        [
            r"\usepackage{fontspec, xeCJK}",
            # r"\setmainfont{Times New Roman}",
            r"\setCJKmainfont{SimSong}",
            r"\setCJKsansfont{Hei}",
        ]
    ),
}
mpl.rcParams.update(params)

x = [1, 2, 3, 4, 5, 6]
y = [1, 4, 9, 16, 25, 36]
plt.figure()
plt.plot(x, y)
plt.title("中文标题 xyz 123")
plt.savefig("test.pdf")
```

<img width="400" alt="image with Chinese font" src="https://github.com/garrettj403/SciencePlots/assets/44312563/99956ccc-9f86-4e6d-8656-310b26b9cd64">

It seems that the `pgf` backend can only save the figure to `pdf` format. I'm wondering how to save the figure as `png`, `svg`, or other formats.

**Comment by machel7** [comment]
Thank you very much, I have used mplfonts to solve the problem. Very appreciate your favor.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Jeremy Feng ***@***.***>
发送时间: Sunday, November 26, 2023 8:16:11 PM
收件人: garrettj403/SciencePlots ***@***.***>
抄送: Seven ***@***.***>; Mention ***@***.***>
主题: Re: [garrettj403/SciencePlots] CJK Noto Fonts - Chinese and Korean don't work - Font 'default' does not have a glyph (Issue #84)


Finally it worked with CJK font! Be careful to set "pgf.preamble". I use the code from matplotlib documentation<https://matplotlib.org/stable/gallery/userdemo/pgf_preamble_sgskip.html>.

import matplotlib as mpl
import matplotlib.pyplot as plt
import scienceplots  # noqa: F401

plt.style.use(["science"])
mpl.use("pgf")

preamble = [
    r"\usepackage{fontspec}",
    r"\setmainfont{Hei}",
]
params = {
    "font.family": "serif",
    "text.usetex": True,
    "pgf.rcfonts": False,
    "pgf.texsystem": "xelatex",
    "pgf.preamble": "\n".join(
        [
            r"\usepackage{fontspec, xeCJK}",
            # r"\setmainfont{Times New Roman}",
            r"\setCJKmainfont{SimSong}",
            r"\setCJKsansfont{Hei}",
        ]
    ),
}
mpl.rcParams.update(params)

x = [1, 2, 3, 4, 5, 6]
y = [1, 4, 9, 16, 25, 36]
plt.figure()
plt.plot(x, y)
plt.title("中文标题 xyz 123")
plt.savefig("test.pdf")

image.png (view on web)<https://github.com/garrettj403/SciencePlots/assets/44312563/99956ccc-9f86-4e6d-8656-310b26b9cd64>

It seems that the pgf backend can only save the figure to pdf format. I'm wondering how to save the figure as png, svg, or other formats.

―

**Comment by Mingzefei** [comment]
> I encountered the same problem when using Simplified Chinese.
> 
> Finally, I used [`mplfonts`](https://github.com/Clarmy/mplfonts) as a temporary solution.
> 
> `mplfonts` is a fonts manager for matplotlib.
> 
> > This is a python package and command line tool to manage your matplotlib fonts. You can easily resolve the "tofu" problem when plotting with CJK(Chinese, Japanese, Korean) languages.
> 
> Hope it helps!

I've practically exhausted all methods, and only this approach has proven successful for me. (WSL2, ubuntu2004)
Those encountering the same problem should consider trying this first. Many thanks once again!

**Comment by shiquda** [comment]
> I encountered the same problem when using Simplified Chinese.
> 
> Finally, I used [`mplfonts`](https://github.com/Clarmy/mplfonts) as a temporary solution.
> 
> `mplfonts` is a fonts manager for matplotlib.
> 
> > This is a python package and command line tool to manage your matplotlib fonts. You can easily resolve the "tofu" problem when plotting with CJK(Chinese, Japanese, Korean) languages.
> 
> Hope it helps!

I tried this, but unfortunately it didn't work for me. I'm on Windows 11, and I use the following code to solve the problem temporarily:

```python
plt.style.use(['science', 'grid', 'cjk-sc-font', 'no-latex'])

plt.rcParams.update({
    'font.family': 'Noto Serif CJK SC',
    'axes.unicode_minus': False,
})
```

**Comment by jiang131072** [comment]
OK, it seems matplotlib treat a .ttc font collection as one font. Just use Noto Serif CJK JP or Noto Sans CJK JP is enough to draw SC/TC/KR Glyph. 
![image](https://github.com/user-attachments/assets/bc1fe0dd-615e-4639-a965-5f8fa9734e40)
