### ISSUE TITLE
any example for 3d plot

### ISSUE THREAD

**Issue by gooyle** [garrettj403/SciencePlots#87]
hi, is there any examples for 3d plot, we try module `mpl_toolkits.mplot3d`, however, it doesnot works well with `scienceplot`

**Comment by echedey-ls** [comment]
From the matplotlib example library, I've used [this one](https://matplotlib.org/stable/gallery/mplot3d/scatter3d.html#sphx-glr-gallery-mplot3d-scatter3d-py).

I've only added two lines, the `import scienceplots` and `plt.style.use(...)`, and styles seem to apply without problems. Next time, pls provide a reproducible example.

```python
import matplotlib.pyplot as plt
import numpy as np

import scienceplots
plt.style.use(['science', "ieee", 'std-colors'])

# Fixing random state for reproducibility
np.random.seed(19680801)


def randrange(n, vmin, vmax):
    """
    Helper function to make an array of random numbers having shape (n, )
    with each number distributed Uniform(vmin, vmax).
    """
    return (vmax - vmin)*np.random.rand(n) + vmin

fig = plt.figure()
ax = fig.add_subplot(projection='3d')

n = 100

# For each set of style and range settings, plot n random points in the box
# defined by x in [23, 32], y in [0, 100], z in [zlow, zhigh].
for m, zlow, zhigh in [('o', -50, -25), ('^', -30, -5)]:
    xs = randrange(n, 23, 32)
    ys = randrange(n, 0, 100)
    zs = randrange(n, zlow, zhigh)
    ax.scatter(xs, ys, zs, marker=m)

ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')

plt.show()
```

**Comment by gooyle** [comment]
thx for your reply, we will try this example


> From the matplotlib example library, I've used [this one](https://matplotlib.org/stable/gallery/mplot3d/scatter3d.html#sphx-glr-gallery-mplot3d-scatter3d-py).
> 
> I've only added two lines, the `import scienceplots` and `plt.style.use(...)`, and styles seem to apply without problems. Next time, pls provide a reproducible example.
> 
> ```python
> import matplotlib.pyplot as plt
> import numpy as np
> 
> import scienceplots
> plt.style.use(['science', "ieee", 'std-colors'])
> 
> # Fixing random state for reproducibility
> np.random.seed(19680801)
> 
> 
> def randrange(n, vmin, vmax):
>     """
>     Helper function to make an array of random numbers having shape (n, )
>     with each number distributed Uniform(vmin, vmax).
>     """
>     return (vmax - vmin)*np.random.rand(n) + vmin
> 
> fig = plt.figure()
> ax = fig.add_subplot(projection='3d')
> 
> n = 100
> 
> # For each set of style and range settings, plot n random points in the box
> # defined by x in [23, 32], y in [0, 100], z in [zlow, zhigh].
> for m, zlow, zhigh in [('o', -50, -25), ('^', -30, -5)]:
>     xs = randrange(n, 23, 32)
>     ys = randrange(n, 0, 100)
>     zs = randrange(n, zlow, zhigh)
>     ax.scatter(xs, ys, zs, marker=m)
> 
> ax.set_xlabel('X Label')
> ax.set_ylabel('Y Label')
> ax.set_zlabel('Z Label')
> 
> plt.show()
> ```
