### ISSUE TITLE
[Bug]: TypeError:  unsupported operand type(s) for *: 'NoneType' and 'int'.

### ISSUE THREAD

**Issue by DongdongGui** [garrettj403/SciencePlots#88]
### Environment

```Python console
System: Windows-10-10.0.19041-SP0
Python: 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
SciencePlots: 2.0.1
Matplotlib: 3.7.1
Latex distro: (populate manually)
```

### Describe the issue here

Using Matplotlib: 3.7.1 with TypeError:  unsupported operand type(s) for *: 'NoneType' and 'int'.
However, Matplotlib: 3.2.2 can be used.

### How can we reproduce it? What have you tried?

import numpy as np
import matplotlib.pyplot as plt
import scienceplots

def model(x, p):
    return x ** (2 * p + 1) / (1 + x ** (2 * p))

pparam = dict(xlabel='Voltage (mV)', ylabel=r'Current ($\mu$A)')

x = np.linspace(0.75, 1.25, 201)

with plt.style.context(['science']):
    fig, ax = plt.subplots()
    for p in [10, 15, 20, 30, 50, 100]:
        ax.plot(x, model(x, p), label=p)
    ax.legend(title='Order')
    ax.autoscale(tight=True)
    ax.set(**pparam)

**Comment by echedey-ls** [comment]
Next time, provide code with triple backticks: ` ``` code ``` `
Can't reproduce with following code (only added `plt.show()` inside the with context):
```python
import numpy as np
import matplotlib.pyplot as plt
import scienceplots

def model(x, p):
    return x ** (2 * p + 1) / (1 + x ** (2 * p))

pparam = dict(xlabel='Voltage (mV)', ylabel=r'Current ($\mu$A)')

x = np.linspace(0.75, 1.25, 201)

with plt.style.context(['science']):
    fig, ax = plt.subplots()
    for p in [10, 15, 20, 30, 50, 100]:
        ax.plot(x, model(x, p), label=p)
    ax.legend(title='Order')
    ax.autoscale(tight=True)
    ax.set(**pparam)
    plt.show()
```

Check indentation and/or copy from the examples file in the repo.

**Comment by DongdongGui** [comment]
![image](https://user-images.githubusercontent.com/51312083/230628435-26760a86-9632-4cc6-995c-57aa5f51b891.png)
```
import numpy as np
import matplotlib.pyplot as plt
import scienceplots

def model(x, p):
    return x ** (2 * p + 1) / (1 + x ** (2 * p))

pparam = dict(xlabel='Voltage (mV)', ylabel=r'Current ($\mu$A)')

x = np.linspace(0.75, 1.25, 201)

with plt.style.context(['science']):
    fig, ax = plt.subplots()
    for p in [10, 15, 20, 30, 50, 100]:
        ax.plot(x, model(x, p), label=p)
    ax.legend(title='Order')
    ax.autoscale(tight=True)
    ax.set(**pparam)
    plt.show()
```

I run the above code and still report TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'.

**Comment by DongdongGui** [comment]
[test 1.zip](https://github.com/garrettj403/SciencePlots/files/11179673/test.1.zip)

**Comment by DongdongGui** [comment]
Test1. zip is the running file

**Comment by echedey-ls** [comment]
I'm pretty sure it has nothing to do with SciencePlots.
I don't have your same setup, and it will take me some time till I can try it. I've only tested locally with basic Python and on Google Colab.
Have you tried updating Anaconda and IPython? It looks like a problem between Matplotlib and the output formatter.

Thanks for sharing the resources.

**Comment by DongdongGui** [comment]
Thank you for your reply!
![image](https://user-images.githubusercontent.com/51312083/230633984-7b323fe3-b503-4d27-9cac-13793abc423e.png)
I tried using the '[ ]' style and '["science","notebook"]' style to run correctly, but other styles still report the  TypeError.

**Comment by echedey-ls** [comment]
I'm glad to hear that!
