### ISSUE TITLE
How to setup style for two-column figures?

### ISSUE THREAD

**Issue by flydream0428** [garrettj403/SciencePlots#91]
Is there a way to set up styles for two-column figures? If I create a figure with a width of 15 cm, the font size will be too large.

**Comment by echedey-ls** [comment]
It would be nice to have an example, so we can test with it and give advice according to it.
Anyway, I suppose you are using the IEEE style, known for having issues with the DPI.
In that case, you can save the figure (I believe it didn't mess up with the DPI scaling, the viewer does), don't use the IEEE style or modify the text properties via code commands:
1. `fig.suptitle('Title', **{'fontsize': 'medium'})` See [matplotlib reference](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.suptitle.html)
2. `ax.set_title('Axes title', , **{'fontsize': 'small'}) See [matplotlib ref](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_title.html#matplotlib.axes.Axes.set_title)
Allowed values for `fontsize` are [here](https://matplotlib.org/stable/api/text_api.html#matplotlib.text.Text.set_fontsize).

Hope to have helped you, feel free to reopen if necessary.

**Comment by flydream0428** [comment]
Thanks for the reply. After some further testing, I realised that many things could be achieved by adjusting the DPI. I guess I need to get more familiar with all the settings before I submit the issue here. I will reopen one if I need more help.
