### ISSUE TITLE
[Bug]: Wiki images broken

### ISSUE THREAD

**Issue by Splines** [garrettj403/SciencePlots#96]
### Describe the issue here

Wiki images are not shown correctly as some example image files got renamed, e.g. `fig1.jpg` was renamed to `fig01.jpg`. I would have changed this on my own but sadly GitHub [does not support pull requests for the wiki repository](https://stackoverflow.com/a/11481887/9655481).

### How can we reproduce it? What have you tried?

Go to the [Wiki](https://github.com/garrettj403/SciencePlots/wiki).

**Comment by echedey-ls** [comment]
Thanks, I will get that fixed once I get home.
